version: '3'

services:

 # front end UI
 istore-angular-ui:
  image: tonyhe2k/istore-angular-ui
  container_name: istore-angular-ui
  ports:
   - "4200:80"
  networks: 
   - istore-network

 # api gateway - all front end should point to this ONLY
 api-gateway:
  image: tonyhe2k/api-gateway
  container_name: api-gateway
  environment: 
   - "spring.cloud.config.uri=http://config-server:8012"
  ports:
   - "8011:8011"
  depends_on: 
   - config-server
   - eureka-server
  networks: 
   - istore-network

 # api microservices
 customer-service:
  image: tonyhe2k/customer-service
  container_name: customer-service
  environment: 
   - "spring.cloud.config.uri=http://config-server:8012"
  depends_on: 
   - config-server
   - eureka-server
   - boot-admin
  networks: 
   - istore-network

 catalog-service:
  image: tonyhe2k/catalog-service
  container_name: catalog-service
  environment: 
   - "spring.cloud.config.uri=http://config-server:8012"
  depends_on: 
   - config-server
   - eureka-server
   - boot-admin
  networks: 
   - istore-network

 order-service:
  image: tonyhe2k/order-service
  container_name: order-service
  environment: 
   - "spring.cloud.config.uri=http://config-server:8012"
  depends_on: 
   - config-server
   - eureka-server
   - boot-admin
  networks: 
   - istore-network

 # common services
 rabbitmq:
  image: 'rabbitmq:3.6-management-alpine'
  container_name: rabbitmq
  ports: 
   # The standard AMQP protocol port
   - "5672:5672"
   # HTTP management UI
   - "15672:15672"
   - "5671:5671"
   - "15671:15671"
   - "4369:4369"
  networks: 
   - istore-network

 config-server:
  image: tonyhe2k/config-server
  container_name: config-server
  environment: 
   - "spring.rabbitmq.host=rabbitmq"
  ports: 
   - "8012:8012"
  networks: 
   - istore-network

 boot-admin:
  image: tonyhe2k/boot-admin
  container_name: boot-admin
  ports:
   - "9999:9999"
  networks: 
   - istore-network

 eureka-server:
  image: tonyhe2k/eureka-server
  container_name: eureka-server
  environment: 
   - "spring.cloud.config.uri=http://config-server:8012"
  ports: 
   - "8761:8761"
  depends_on: 
   - config-server
  networks: 
   - istore-network

 zipkin-server:
  image: openzipkin/zipkin
  container_name: zipkin-server
  ports: 
   - "9411:9411"
  networks: 
   - istore-network

networks: 
  istore-network: